<?php

use App\Http\Controllers\ActiveTicketsController;
use App\Http\Controllers\EmailVerificationController;
use App\Http\Controllers\EventsController;
use App\Http\Controllers\OrderItemsController;
use App\Http\Controllers\OrdersController;
use App\Http\Controllers\OriginalTicketsController;
use App\Http\Controllers\PasswordResetController;
use App\Http\Controllers\PayoutsController;
use App\Http\Controllers\ReviewsController;
use App\Http\Controllers\TicketForSaleController;
use App\Http\Controllers\TicketHistoryController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserSettingsController;
use App\Http\Controllers\VenueMapController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\StripeController;
use Illuminate\Support\Facades\Route;


Route::post('login', [AuthController::class, 'login'])->middleware('throttle:3,1');
Route::post('register', [AuthController::class, 'register']);
Route::post('logout', [AuthController::class, 'logout']);
Route::get('events/search', [EventsController::class, 'search']);
Route::apiResource('events', EventsController::class);
Route::get('venues/search', [VenueMapController::class, 'search']);
Route::apiResource('venues', VenueMapController::class);
Route::apiResource('activeTickets', ActiveTicketsController::class);
Route::get('originalTickets/search', [OriginalTicketsController::class, 'search']);
Route::get("originalTickets/forSale/{eventId}", [OriginalTicketsController::class, "getOnlyAvailableTicketsInForSale"]);
Route::get("originalTickets/dashboard", [OriginalTicketsController::class, "dashboard"]);
Route::post("originalTickets/bulk", [OriginalTicketsController::class, "bulkStore"]);
Route::put("originalTickets/bulk", [OriginalTicketsController::class, "bulkUpdate"]);
Route::post("originalTickets/bulkStatusChange", [OriginalTicketsController::class, "bulkStatusChange"]);
Route::apiResource('originalTickets', OriginalTicketsController::class);
Route::get('ticketForSale/search', [TicketForSaleController::class, 'search']);
Route::post('ticketForSale/basketChange/{ticketForSale}', [TicketForSaleController::class, 'basketChange']);
Route::post('ticketForSale/addToBasket/{ticketForSale}', [TicketForSaleController::class, 'addToBasket']);
Route::post('ticketForSale/removeFromBasket/{ticketForSale}', [TicketForSaleController::class, 'removeFromBasket']);
Route::post('ticketForSale/checkOut', [TicketForSaleController::class, 'checkOut']);
Route::post('ticketForSale/finalize', [TicketForSaleController::class, 'finalize']);
Route::post('checkout', [StripeController::class, 'checkOut']);
Route::get('checkout/session', [StripeController::class, 'checkoutSession']);
Route::post('orders/checkOut', [StripeController::class, 'checkOut']);
Route::apiResource('ticketForSale', TicketForSaleController::class);
Route::apiResource('user', UserController::class);
Route::post('email/verify/send', [EmailVerificationController::class, 'sendLink']);
Route::post('email/verify', [EmailVerificationController::class, 'verify']);
Route::apiResource("orderItems", OrderItemsController::class);
Route::apiResource("orders", OrdersController::class);
Route::post('password/forgot', [PasswordResetController::class, 'store']);
Route::post('password/reset', [PasswordResetController::class, 'update']);
Route::get('payouts', [PayoutsController::class, 'index']);
Route::get('payouts/{payout}', [PayoutsController::class, 'show']);
Route::put('payouts/{payout}', [PayoutsController::class, 'update']);
Route::get('my/payouts', [PayoutsController::class, 'myPayouts'])->middleware('auth:sanctum');
Route::apiResource("reviews", ReviewsController::class);
Route::post('ticketHistory', [TicketHistoryController::class, 'store']);
Route::get('ticketHistory', [TicketHistoryController::class, 'index']);
Route::get('ticketHistory/{ticketHistory}', [TicketHistoryController::class, 'show']);
Route::get('ticketHistory/my/history', [TicketHistoryController::class, 'myHistory'])->middleware('auth:sanctum');
Route::apiResource("userSettings", UserSettingsController::class);